<?php

/* 
 *	PagesMapManager
 *
 *  This module is for managing pages mindmap style. It allows easily create
 *  website hiearchy which has large static content.
 *
 *  Module will display mindmap from current pages. After user add a new page module
 *  will do ajax request to add that page, same in case of delete. So basicly
 *  the map should always be synced with real pages.
 *
 *	@author Joonas "Entil'zha" Kolkka <joonas.kolkka@comspot.fi
 *	@todo Add toolbar functional to edit pages
 */

/*
 *  Module uses Chaptykov (https://github.com/Chaptykov/mindmap) javascipt mindmap
 *	plugin for jQuery licenced under MIT.
 *	
 *	The MIT License (MIT)
 *	Copyright (c) 2013 Chaptykov
 *	Permission is hereby granted, free of charge, to any person obtaining a copy of
 *	this software and associated documentation files (the "Software"), to deal in
 *	the Software without restriction, including without limitation the rights to
 *	use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *	the Software, and to permit persons to whom the Software is furnished to do so,
 *	subject to the following conditions:
 *	The above copyright notice and this permission notice shall be included in all
 *	copies or substantial portions of the Software.
 *	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 *	FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 *	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 *	IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 *	CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *	
 */

 
/*
 * Class PagesMapManager
 *
 */
class PagesMapManager extends Process{
    
    public function __construct() {
       
    }
	
    public static function getModuleInfo() {
		/* Define module info */
        return array(
            'title' => __('Pages Map Manger'), 
            'version' => '0.2', 
            'summary' => 'Allows you to manage pages in mindmap.',
			'author' => "Joonas \"Entil'zha\" Kolkka",
            'href' => 'fill git hub here',
            'singular' => true, 
            'autoload' => false, 
            );
    }
    
    public function execute() {
		/* Tell user what's this about and how to use */
		$content = '<h2>' . __('Pages management with mindmap') . '</h2>';
		$content .= '<p>' . __('You can easily manage your pages with this mindmap tool.') . '</p>';
		$content .= '<ul>';
		$content .= '<li>' . __('Create page to same level') . ' - Enter</li>';
		$content .= '<li>' . __('Create suppage under selected') . ' - Tab</li>';
		$content .= '<li>' . __('Delete selected page') . ' - Delete</li>';
		$content .= '</ul>';
		/* create div for mindmap */
		$content .= '<div class="mindmap">';
		/* Create root node */
		$content .= '<div class="node node_root">';
		/* Set name from homepage */
		$content .= '<div class="node__text">' . wire('pages')->get(1)->title . '</div>';
		$content .= '<input type="text" class="node__input">';
		$content .= '</div>';
		/* Load pages */
		$content .= $this->getPages(wire('pages')->get(1));
		$content .= '</div>';
		/* Set mindmap js */
		$content .= '<script>';
		$content .= '$(function(){';
		$content .= '$(\'.mindmap\').mindmap();';
		$content .= '});';
		$content .= '</script>';
		/* Return content for output */
		return $content;
    }
	
	public function executePages() {
		/* If not ajax redirect to mainpage */
		if(wire('config')->ajax) {

			/* Check if pageID and title is set, else return error */
			if(wire('input')->post->pageID && wire('input')->post->title) {
				$p = new Page();
				$p->template = $this->templates->get('basic-page');
				$p->title = wire('input')->post->title;
				$p->name = wire('sanitizer')->name(wire('input')->post->title);
				/* TODO: Check if there's a better sanitizer than text */
				$p->parent = $this->pages->get(wire('sanitizer')->text(wire('input')->post->parentid));
				//$p->save();
				
				$out = '<li class="ui-state-highlight NoticeMessage"><div class="container"><p><i class="fa fa-check-square"></i> ' . __('Page created') . '</p></div></li>';

			}
			else {
				//$out = '<div class="alert alert-error" role="alert">' . __('Error: Page must have Title!') . '</div>';
			}
		}
		else {
			$this->session->redirect('./');
		}
		/* Everything done, let's kill this */
		return $out;
	}
	
	/**
	 *	getPages
	 *
	 *	Recursively get all pages under given one
	 *
	 *	@param object $page Page that we use as a parent
	 *	@param int $level How many levels we go down
	 *
	 *	@return char Returns html
	 */
	private function getPages($page, $level = 0) {
		/* Get find pages that has given page as parent */
		$pages = wire('pages')->find('parent=' . $page);
		$out = '';
		/* Loop trough pages */
		foreach($pages as $page) {
			/* Create required markup */
			$out .= '<li class="children__item">';
			$out .= '<div class="node">';
			/* Echo page's id and title */
			$out .= '<div id="' . $page->id . '" data-parentid="' . $page->parent->id . '" class="node__text">' . $page->title . '</div>';
			$out .= '<input type="text" class="node__input">';
			$out .= '</div>';
			/* Check if page has childrens */
			if($page->hasChildren()) {
				/* Loop trough childrens */
				$out .= $this->getPages($page, $level+1);
			}
			$out .= '</li>';
			
		}
		/* If level is first after parent the output children_rightbranch, else
		 * output just chilren. */
		if ($out && !$level) $out = ' <ol class="children children_rightbranch">' . $out . '</ol>';
		else $out = ' <ol class="children">' . $out . '</ol>';
		
		/* Return output */
		return $out;
	}
    
	public function install() {
		/* This is purely stolen from soma's ModulesManager-module <3 */
		// page already found for some reason
		$ap = $this->pages->find('name='.__CLASS__)->first();
		if($ap->id) {
            if(!$ap->process) {
                    $ap->process = $this;
                    $ap->save();
            }
            return;
        }
		$p = new Page();
		$p->template = $this->templates->get('admin');
		$p->title = __CLASS__;
		$p->name = __CLASS__;
		$p->parent = $this->pages->get(22);
		$p->process = $this;
		$p->save();
	}
}
